/**
 * Al-Quran EPUB Generator - Browser-side
 * Data source: local JSON files in public/script/ and public/translation/
 */
import JSZip from "jszip";
import epub from "epub-gen-memory/bundle";

const btnGenerate = document.getElementById("btn-generate");
const optPage = document.getElementById("opt-page");
const optLatin = document.getElementById("opt-latin");
const optFont = document.getElementById("opt-font");
const optFilename = document.getElementById("opt-filename");
const editionScriptInput = document.getElementById("edition-arabic");
const editionTranslationInput = document.getElementById("edition-translation");
const progressCard = document.getElementById("section-progress");
const progressBar = document.getElementById("progress-bar");
const progressPct = document.getElementById("progress-pct");
const progressTitle = document.getElementById("progress-title");
const progressDetail = document.getElementById("progress-detail");

// ── Config ──────────────────────────────────────────────────────────────────

// Transliteration file (always loaded separately for the latin line)
const TRANSLITERATION_FILE = "english-Transliteration";

// Filenames (without .json) from public/script/ — add/remove manually here
const AVAILABLE_SCRIPTS = [
  "imlaei",
  "imlaei_simple",
  "indopak",
  "indopak_nastaleeq",
  "qpc_hafs",
  "qpc_nastaleeq",
  "text_imlaei",
  "text_imlaei_simple",
  "text_indopak",
  "text_indopak_nastaleeq",
  "text_qpc_hafs",
  "text_qpc_nastaleeq",
  "text_uthmani_simple",
  "text_uthmani_tajweed",
  "uthmani",
  "uthmani_simple",
  "uthmani_tajweed",
  "code_v1",
  "code_v2",
  "v1",
  "v2",
];

// ── Populate dropdowns ───────────────────────────────────────────────────────

/**
 * Loads public/data/translations.json (generated by quranEpubGenerator.py --gen-manifest)
 * Each entry: { file, iso, language, name }
 * Dropdown label: "<Language> - <Translator>"  e.g. "English - Sahih International"
 * Dropdown value: file (filename without .json)
 */
async function populateDropdowns() {
  editionScriptInput.innerHTML = "";
  AVAILABLE_SCRIPTS.forEach((name) => {
    const opt = document.createElement("option");
    opt.value = name;
    opt.textContent = name;
    editionScriptInput.appendChild(opt);
  });

  editionTranslationInput.innerHTML =
    '<option value="">Tanpa terjemahan</option>';
  try {
    const res = await fetch("./data/translations.json");
    if (!res.ok) throw new Error(`translations.json not found (${res.status})`);
    const translations = await res.json();

    translations.forEach(({ file, language, name }) => {
      const opt = document.createElement("option");
      opt.value = file;
      // Split display: "English - Sahih International"
      opt.textContent = name ? `${language} - ${name}` : language;
      editionTranslationInput.appendChild(opt);
    });
  } catch (err) {
    console.warn("Failed to load translations.json:", err);
    const opt = document.createElement("option");
    opt.value = "";
    opt.textContent = "⚠ translations.json not found — run --gen-manifest";
    opt.disabled = true;
    editionTranslationInput.appendChild(opt);
  }
}

// ── Local JSON loaders ──────────────────────────────────────────────────────

/**
 * Load a script JSON from public/script/<name>.json
 * Format: flat array → [{surahId, ayahId, script}, ...]
 * Returns: Map keyed by "surahId:ayahId" → script text
 */
async function loadScriptJson(name) {
  const res = await fetch(`./script/${name}.json`);
  if (!res.ok)
    throw new Error(`Script file not found: public/script/${name}.json`);
  const data = await res.json();
  const map = new Map();
  for (const entry of data) {
    map.set(`${entry.surahId}:${entry.ayahId}`, entry.script);
  }
  return map;
}

/**
 * Load a translation JSON from public/translation/<name>.json
 * Format: nested dict → {"1": [{surah_id, ayah_id, text}, ...], ...}
 * Returns: Map keyed by "surahId:ayahId" → text
 */
async function loadTranslationJson(name) {
  const res = await fetch(`./translation/${name}.json`);
  if (!res.ok)
    throw new Error(
      `Translation file not found: public/translation/${name}.json`,
    );
  const data = await res.json();
  const map = new Map();
  for (const [surahId, ayahs] of Object.entries(data)) {
    for (const ayah of ayahs) {
      map.set(`${surahId}:${ayah.ayah_id}`, {
        text: stripHtml(ayah.text),
        page_number: ayah.page_id ?? null,
      });
    }
  }
  return map;
}

/**
 * Load surah metadata from public/data/surah.json
 */
async function loadSurahList() {
  const res = await fetch("./data/surah.json");
  if (!res.ok) throw new Error(`Surah metadata not found (${res.status})`);
  return await res.json();
}

/**
 * Merge script + transliteration + translation maps into per-surah verse arrays.
 * Returns: { [surahNumber]: [{ayah_number, script, latin, translation}, ...] }
 */
function buildVerseDataMap(scriptMap, latinMap, translationMap, surahList) {
  const verseDataMap = {};

  for (const surah of surahList) {
    const surahId = String(surah.surah_id);
    const verses = [];

    for (let ayahNum = 1; ayahNum <= surah.surah_verse_count; ayahNum++) {
      const key = `${surahId}:${ayahNum}`;
      const translationEntry = translationMap
        ? (translationMap.get(key) ?? null)
        : null;
      const latinEntry = latinMap ? (latinMap.get(key) ?? null) : null;

      verses.push({
        ayah_number: ayahNum,
        page_number:
          translationEntry?.page_number ?? latinEntry?.page_number ?? null,
        script: scriptMap.get(key) ?? "",
        latin: latinEntry?.text ?? "",
        translation: translationEntry?.text ?? "",
      });
    }

    verseDataMap[surah.surah_id] = verses;
  }

  return verseDataMap;
}

// ── Helpers ─────────────────────────────────────────────────────────────────

function setProgress(pct, title, detail = "") {
  progressCard.style.display = "block";
  progressBar.style.width = pct + "%";
  progressPct.textContent = Math.round(pct) + "%";
  progressTitle.textContent = title;
  progressDetail.textContent = detail;
}

function escapeHtml(value = "") {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function stripHtml(value = "") {
  const doc = new DOMParser().parseFromString(String(value), "text/html");
  return doc.body.textContent || "";
}

function buildEpubCss(fontFile, fontFamilyName = "Arabic Font") {
  const fontFace = `@font-face {
    font-family: "${fontFamilyName}";
    font-weight: 400;
    font-style: normal;
    src: url(fonts/${fontFile}) format("truetype");
  }`;

  return `
    ${fontFace}
    body { font-family: serif; margin: 1em; padding: 0; }
    .surah-header { text-align: center; margin-bottom: 1.2em; padding: 0.6em 0;
      border-top: 1px solid #000; border-bottom: 1px solid #000; }
    .surah-number { font-size: 0.85em; font-weight: bold; display: block; margin-bottom: 0.3em; }
    .surah-name-arabic { font-family: "${fontFamilyName}", "Scheherazade New", "Traditional Arabic", serif;
      font-size: 2em; direction: rtl; display: block; margin: 0.2em 0; }
    .surah-name-latin { font-size: 1.05em; font-weight: bold; display: block; }
    .surah-meta { font-size: 0.8em; display: block; margin-top: 0.3em; }
    .basmalah { font-family: "${fontFamilyName}", "Scheherazade New", "Traditional Arabic", serif;
      font-size: 1.35em; line-height: 1.8; direction: rtl; text-align: center; margin: 1em 0; }
    .ayah-block { margin-bottom: 1.2em; padding-bottom: 0.8em; border-bottom: 1px solid #ccc; }
    .ayah-block:last-child { border-bottom: none; }
    .ayah-meta { font-size: 0.78em; line-height: 1; font-weight: bold; margin-bottom: 0.35em; }
    .arabic-text { font-family: "${fontFamilyName}", "Scheherazade New", "Traditional Arabic", serif;
      font-size: 2em; line-height: 1.4; direction: rtl; text-align: right; display: block; margin-bottom: 0.35em; }
    .latin-line { font-size: 0.85em; line-height: 1.2; }
    .translation-line { font-size: 0.85em; line-height: 1.2; margin-top: 0.25em; }
  `;
}

function buildSurahHtml(surahMeta, verses, opts) {
  const { num, name, nameAr, nameBahasa, revType, verseCount } = surahMeta;
  const basmalahText = "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ";
  const basmalahHtml =
    num !== 1 && num !== 9 ? `<p class="basmalah">${basmalahText}</p>` : "";

  const blocks = verses
    .map((v) => {
      const pageText =
        opts.showPage && v.page_number ? ` - Hal. ${v.page_number}` : "";
      const script =
        num !== 1 && num !== 9 && v.ayah_number === 1
          ? v.script.replace(
              /^﻿?بِسْمِ\s+ٱللَّهِ\s+ٱلرَّحْمَٰنِ\s+ٱلرَّحِيمِ\s*/u,
              "",
            )
          : v.script;
      const latinHtml =
        opts.showLatin && v.latin
          ? `<p class="latin-line">${escapeHtml(v.latin)}</p>`
          : "";
      const translationHtml =
        opts.editionTranslation && v.translation
          ? `<p class="translation-line">${escapeHtml(v.translation)}</p>`
          : "";

      return `
      <div class="ayah-block">
        <p class="ayah-meta">${escapeHtml(name)} - Ayat ${v.ayah_number}${pageText}</p>
        <p class="arabic-text">${escapeHtml(script)}</p>
        ${latinHtml}
        ${translationHtml}
      </div>`;
    })
    .join("\n");

  return `
    <div class="surah-header">
      <p class="surah-number">Surah ${num}</p>
      <p class="surah-name-arabic">${escapeHtml(nameAr)}</p>
      <p class="surah-name-latin">${escapeHtml(name)} - ${escapeHtml(nameBahasa)}</p>
      <p class="surah-meta">${revType} - ${verseCount} Ayat</p>
    </div>
    ${basmalahHtml}
    ${blocks}
  `;
}

const MAKKIYAH = new Set([
  1, 6, 7, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 23, 25, 26, 27, 28,
  29, 30, 31, 32, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 50, 51,
  52, 53, 54, 55, 56, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
  81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 100, 101,
  102, 103, 104, 105, 106, 107, 108, 109, 111, 112, 113, 114,
]);

// ── Main generate ────────────────────────────────────────────────────────────

async function generate() {
  btnGenerate.disabled = true;
  btnGenerate.classList.add("loading");
  progressCard.style.display = "block";

  const opts = {
    showPage: optPage.checked,
    showLatin: optLatin.checked,
    editionScript: editionScriptInput.value,
    editionTranslation: editionTranslationInput.value,
    fontName: optFont.value,
  };
  const filename = (optFilename.value.trim() || "AlQuran-Kindle") + ".epub";
  const total = 114;

  try {
    setProgress(2, "Memuat metadata surah...", "");
    const surahs = await loadSurahList();

    setProgress(
      8,
      "Memuat font Arab...",
      optFont.options[optFont.selectedIndex].text,
    );

    const FONT_LABELS = {
      "scheherazade-new-arabic-400-normal": "Scheherazade New",
      "amiri-quran-400-normal": "Amiri Quran",
      "quran-complex-ver2-arabic-400-normal": "Quran Complex Font Version 2",
      "kfgqpc-hafs-uthmanic-script-arabic-400-normal":
        "KFGQPC Uthmanic HAFS Script",
      "kfgqpc-hafs-smart-400-normal": "KFGQPC Hafs Smart",
      "noto-naskh-arabic-400-normal": "Noto Naskh Arabic",
    };

    const fontFile = `${opts.fontName}.ttf`;
    const fontPath = `${import.meta.env.BASE_URL}fonts/${fontFile}`;
    const fontFamilyName = FONT_LABELS[opts.fontName] || "Arabic Font";

    try {
      const fontRes = await fetch(fontPath);
      if (!fontRes.ok) throw new Error(`HTTP ${fontRes.status}`);
      const fontBuf = await fontRes.arrayBuffer();
      if (fontBuf.byteLength < 1000) throw new Error(`File font terlalu kecil`);
      setProgress(
        12,
        `Font ${fontFamilyName} berhasil dimuat ✓`,
        `${(fontBuf.byteLength / 1024).toFixed(0)} KB`,
      );
    } catch (e) {
      console.error("Font gagal dimuat:", e);
      setProgress(12, `⚠️ Font ${fontFamilyName} gagal dimuat`, e.message);
      await new Promise((r) => setTimeout(r, 2000));
    }

    const css = buildEpubCss(fontFile, fontFamilyName);

    setProgress(18, "Memuat teks Arab...", `script/${opts.editionScript}.json`);
    const scriptMap = await loadScriptJson(opts.editionScript);

    let latinMap = null;
    if (opts.showLatin) {
      setProgress(
        35,
        "Memuat transliterasi latin...",
        `translation/${TRANSLITERATION_FILE}.json`,
      );
      latinMap = await loadTranslationJson(TRANSLITERATION_FILE);
    }

    let translationMap = null;
    if (opts.editionTranslation) {
      setProgress(
        50,
        "Memuat terjemahan...",
        `translation/${opts.editionTranslation}.json`,
      );
      translationMap = await loadTranslationJson(opts.editionTranslation);
    }

    setProgress(60, "Menggabungkan data ayat...", "");
    const verseDataMap = buildVerseDataMap(
      scriptMap,
      latinMap,
      translationMap,
      surahs,
    );

    setProgress(65, "Menyusun konten EPUB...", "");
    const surahMetaMap = Object.fromEntries(surahs.map((s) => [s.surah_id, s]));
    const sortedNums = Array.from({ length: total }, (_, i) => i + 1);

    const chapters = sortedNums.map((num, i) => {
      const meta = surahMetaMap[num];
      const verses = verseDataMap[num];
      const surahMeta = {
        num,
        name: meta.surah_name,
        nameAr: meta.surah_name_arabic.trim(),
        nameBahasa: meta.surah_name_bahasa,
        revType: MAKKIYAH.has(num) ? "Makkiyah" : "Madaniyah",
        verseCount: meta.surah_verse_count,
      };
      const pct = 65 + ((i + 1) / total) * 20;
      setProgress(
        pct,
        "Menyusun konten...",
        `Surah ${num}: ${meta.surah_name}`,
      );
      return {
        title: `${num}. ${meta.surah_name} (${meta.surah_name_arabic.trim()})`,
        content: buildSurahHtml(surahMeta, verses, opts),
        filename: `surah_${String(num).padStart(3, "0")}.xhtml`,
      };
    });

    setProgress(
      88,
      "Membuat file EPUB...",
      "Ini mungkin membutuhkan beberapa detik",
    );

    const blob = await epub(
      {
        title: "Al-Quran Al-Karim - Latin Transliteration",
        author: "Allah",
        publisher: "",
        cover:
          "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1275263838i/646462.jpg",
        description: `The Quran (English pronunciation: /kɔrˈɑːn/; Arabic: القرآن‎ al-qurʾān, IPA: [qurˈʔaːn], literally meaning "the recitation"), also transliterated Qur'an, Koran, Al-Coran, Coran, Kur'an, and Al-Qur'an, is the central religious text of Islam, which Muslims believe to be the verbatim word of God (Arabic: الله‎, Allah).
        The Quran is composed of verses (Ayat) that make up 114 chapters (suras) of unequal length which are classified either as Meccan (المكية) or Medinan (المدنية) depending upon the place and time of their claimed revelation. Muslims believe the Quran to be verbally revealed through the angel Jibrīl (Gabriel) from God to Muhammad gradually over a period of approximately 23 years beginning on 22 December 609 CE, when Muhammad was 40, and concluding in 632 CE, the year of his death.
        Muslims regard the Quran as the main miracle of Muhammad, the proof of his prophethood and the culmination of a series of divine messages that started with the messages revealed to Adam, regarded in Islam as the first prophet, and continued with Suhuf Ibrahim (Scrolls of Abraham), the Tawrat (Torah or Pentateuch) of Moses, the Zabur (Tehillim or Book of Psalms) of David, and the Injil (Gospel) of Jesus. The Quran assumes familiarity with major narratives recounted in Jewish and Christian scriptures, summarizing some, dwelling at length on others and in some cases presenting alternative accounts and interpretations of events. The Quran describes itself as a book of guidance, sometimes offering detailed accounts of specific historical events, and often emphasizing the moral significance of an event over its narrative sequence.`,
        lang: "",
        tocTitle: "Daftar Surah",
        css,
        numberChaptersInTOC: false,
        prependChapterTitles: false,
        version: 3,
        fonts: [{ filename: `${opts.fontName}.ttf`, url: fontPath }],
      },
      chapters,
    );

    // Post-process: inject Goodreads + Amazon identifiers into the OPF
    const zip = await JSZip.loadAsync(blob);
    const opfPath = "OEBPS/content.opf";
    const opfFile = zip.file(opfPath);
    if (opfFile) {
      let opfContent = await opfFile.async("string");
      opfContent = opfContent.replace(
        "</metadata>",
        `<dc:identifier id="goodreads">goodreads:646462</dc:identifier>
         <dc:identifier id="amazon">amazon:B0DTR624WB</dc:identifier>
        </metadata>`,
      );
      zip.file(opfPath, opfContent);
    }

    const finalBlob = await zip.generateAsync({
      type: "blob",
      mimeType: "application/epub+zip",
    });

    setProgress(100, "Selesai! Mengunduh...", filename);

    const url = URL.createObjectURL(finalBlob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 5000);

    setTimeout(() => {
      progressTitle.textContent = "EPUB berhasil dibuat!";
      progressDetail.textContent = `${total} surah - ${filename}`;
    }, 500);
  } catch (err) {
    console.error(err);
    setProgress(0, "Gagal membuat EPUB", err.message);
  } finally {
    btnGenerate.disabled = false;
    btnGenerate.classList.remove("loading");
  }
}

btnGenerate.addEventListener("click", generate);

// Populate dropdowns from local file lists on load
populateDropdowns();
